import type { ApplicationType, SignInMode } from "@cognito-kit/core"

export interface InitTemplateOptions {
  name: string
  signIn: SignInMode
  application: ApplicationType
  callbackUrls: string[]
  logoutUrls: string[]
}

const DEFAULT_CALLBACKS: Record<ApplicationType, string[]> = {
  web: ["http://localhost:3000/auth/callback"],
  spa: ["http://localhost:5173/auth/callback"],
  mobile: ["myapp://auth/callback"],
}

const DEFAULT_LOGOUTS: Record<ApplicationType, string[]> = {
  web: ["http://localhost:3000"],
  spa: ["http://localhost:5173"],
  mobile: ["myapp://"],
}

/**
 * Renders the starter `auth.config.ts` file. Pure function — no I/O — so it
 * can be snapshot-tested.
 */
export function renderAuthConfigFile(options: InitTemplateOptions): string {
  const callbacks =
    options.callbackUrls.length > 0 ? options.callbackUrls : DEFAULT_CALLBACKS[options.application]
  const logouts =
    options.logoutUrls.length > 0 ? options.logoutUrls : DEFAULT_LOGOUTS[options.application]

  const callbackLines = callbacks.map((u) => indent(`"${u}"`, 6)).join(",\n")
  const logoutLines = logouts.map((u) => indent(`"${u}"`, 6)).join(",\n")

  return `// Generated by \`cognito-kit init\`.
// This is your app's entire Cognito surface. Everything else is safe defaults.
import { defineAuth } from "@cognito-kit/core"

export default defineAuth({
  schemaVersion: 1,
  name: ${JSON.stringify(options.name)},
  signIn: ${JSON.stringify(options.signIn)},

  application: {
    type: ${JSON.stringify(options.application)},
    callbackUrls: [
${callbackLines}
    ],
    logoutUrls: [
${logoutLines}
    ],
  },
})
`
}

/** Renders a starter `users.ts` development users file. */
export function renderUsersFile(): string {
  return `// Development users for \`cognito-kit dev\`.
// Passwords are plain text — this file is for local development only.
export default [
  {
    id: "dev_alice",
    email: "alice@example.com",
    password: "password",
    claims: {},
  },
  {
    id: "dev_admin",
    email: "admin@example.com",
    password: "password",
    claims: {
      role: "admin",
    },
  },
]
`
}

function indent(text: string, spaces: number): string {
  return " ".repeat(spaces) + text
}
