#!/usr/bin/env node
/**
 * Generates markdown reference docs from the built code:
 *
 *  - docs/generated/commands.md     — introspected from the commander program
 *  - docs/generated/diagnostics.md  — introspected from DIAGNOSTIC_RULES
 *
 * API reference (docs/generated/api) is generated by TypeDoc via `typedoc`.
 * Run with: pnpm docs:generate
 */
import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { DIAGNOSTIC_RULES } from "../packages/core/dist/index.js"
import { buildProgram } from "../packages/cli/dist/index.js"

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const generatedDir = join(root, "docs", "generated")
mkdirSync(generatedDir, { recursive: true })

const GENERATED_NOTICE =
  "<!-- GENERATED by scripts/generate-docs.mjs — DO NOT EDIT. Run `pnpm docs:generate`. -->"

/* ------------------------------ commands ------------------------------ */

const program = buildProgram()
const commands = program.commands.map((cmd) => ({
  name: cmd.name(),
  description: cmd.description(),
  args: (cmd._args ?? [])
    .filter(Boolean)
    .map((arg) => ({
      name: arg._name ?? arg.name ?? "",
      description: arg.description ?? "",
    })),
  options: cmd.options
    .filter((opt) => !opt.negate)
    .map((opt) => ({ flags: opt.flags, description: opt.description })),
}))

const cmdLines = [
  GENERATED_NOTICE,
  "",
  "# CLI commands",
  "",
  "Usage: `cognito-kit <command> [options]`",
  "",
  ...commands.flatMap((cmd) => {
    const lines = [`## ${cmd.name}`, "", cmd.description, ""]
    if (cmd.args.length > 0) {
      lines.push("Arguments:", "")
      for (const arg of cmd.args) {
        lines.push(`- \`${arg.name}\` — ${arg.description || ""}`)
      }
      lines.push("")
    }
    if (cmd.options.length > 0) {
      lines.push("Options:", "")
      for (const opt of cmd.options) {
        lines.push(`- \`${opt.flags}\` — ${opt.description}`)
      }
      lines.push("")
    }
    return lines
  }),
]

writeFileSync(join(generatedDir, "commands.md"), cmdLines.join("\n"))

/* ----------------------------- diagnostics ---------------------------- */

const diagLines = [
  GENERATED_NOTICE,
  "",
  "# Diagnostics",
  "",
  "`cognito-kit doctor` analyzes a normalized Cognito configuration and reports findings.",
  "",
  "Each finding has a rule id, severity, title, explanation and recommendation.",
  "",
  "## Rules",
  "",
  "| ID | Severity | Title |",
  "| --- | --- | --- |",
  ...DIAGNOSTIC_RULES.map(
    (rule) => `| \`${rule.id}\` | ${rule.severity} | [${rule.title}](#${rule.id}) |`,
  ),
  "",
  ...DIAGNOSTIC_RULES.flatMap((rule) => {
    const lines = [`## ${rule.id}`, "", `**Severity:** ${rule.severity}`, ""]
    lines.push(`**Title:** ${rule.title}`, "", rule.explanation, "")
    lines.push(`**Recommendation:** ${rule.recommendation}`, "")
    if (rule.docsUrl) lines.push(`**Docs:** ${rule.docsUrl}`, "")
    lines.push("")
    return lines
  }),
]

writeFileSync(join(generatedDir, "diagnostics.md"), diagLines.join("\n"))

console.log("Generated:")
console.log(`  ${join(generatedDir, "commands.md")}`)
console.log(`  ${join(generatedDir, "diagnostics.md")}`)
console.log(`  ${join(generatedDir, "api")} (TypeDoc)`)